export const INIT_USER_ID = 'INIT_USER_ID';

// MISC
export const CLOSE_POPUP = 'CLOSE_POPUP';
export const CALL_POPUP = 'CALL_POPUP';
export const CALL_MODAL = 'CALL_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

// CART MUTATIONS
export const INIT_CARTS_STATE = 'INIT_CARTS_STATE';
export const UPDATE_CARTS_STATE = 'UPDATE_CARTS_STATE';
export const TOGGLE_ADDCART = 'TOGGLE_ADDCART';
export const SAVE_CART = 'SAVE_CART';
export const UPDATE_CURRENT_CART_THUMB = 'UPDATE_CURRENT_CART_THUMB';
export const UPDATE_CURRENT_CART_LOCATION = 'UPDATE_CURRENT_CART_LOCATION';

// INVENTORY MUTATIONS
export const UPDATE_INVENTORY_STATE = 'UPDATE_INVENTORY_STATE';
export const INIT_INVENTORY_STATE = 'INIT_INVENTORY_STATE';
export const TOGGLE_ADD_PRODUCT = 'TOGGLE_ADD_PRODUCT';
export const SAVE_PRODUCT = 'SAVE_PRODUCT';


export const UPDATE_PRODUCT_OPTIONS = 'UPDATE_PRODUCT_OPTIONS';
export const INIT_PRODUCT_OPTIONS = 'INIT_PRODUCT_OPTIONS';
