export const INIT_CARTS_STATE = 'INIT_CARTS_STATE';
export const TOGGLE_ADDCART = 'TOGGLE_ADDCART';
export const SAVE_CART = 'SAVE_CART';
export const UPDATE_CURRENT_CART_THUMB = 'UPDATE_CURRENT_CART_THUMB';
export const UPDATE_CURRENT_CART_LOCATION = 'UPDATE_CURRENT_CART_LOCATION';
